platform :ios, '5.0'
pod 'AFNetworking', '~> 1.0'
pod 'SVProgressHUD', '~> 0.9'
pod 'SVPullToRefresh', '~> 0.4'
pod 'QuickDialog', '~> 0.8'
pod 'Reachability', '~> 3.1.0'
pod 'FMDB', '~> 2.1'
pod 'hpple', '~> 0.2.0'
pod 'REMenu', '~> 1.3.5'
pod 'TSMessages', '~> 0.9.3'
pod 'ECSlidingViewController', '~> 0.10.0'
