platform :ios, '5.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4'
pod 'QuickDialog', '~> 0.9.1'
pod 'Reachability', '~> 3.1.1'
pod 'FMDB', '~> 2.1'
pod 'hpple', '~> 0.2.0'
pod 'REMenu', '~> 1.7.1'
#pod 'TSMessages', '~> 0.9.4'
pod 'MMDrawerController', '~> 0.5.1'
pod 'ECSlidingViewController', '~> 1.3'
pod 'ALAlertBanner', '~>0.3.1'
